### PR TITLE
Label and value disappears when value reach 0 for any time unit

### PR DESCRIPTION
**Pull request by mcendon**
Label and value disappears when value reach 0 for any time unit (SECONDS, MINUTES, HOURS, DECADES, etc), with the toString() method. This code will fix it

### CODE REVIEW

**Comment by mckamey** [comment]
This is by design. Nothing to fix here. See the docs on how to specify the message when the timer reaches zero:

http://countdownjs.org/readme.html

**Comment by mcendon** [comment]
Hi @mckamey when i say "reach 0" i'm referring to the less significative value in the timer. not the totally of the time

For example this is the behavior of a countdown implemented with CountdownJs:

3 hours, 20 minutes and 5 seconds
3 hours, 20 minutes and 4 seconds
3 hours, 20 minutes and 3 seconds
3 hours, 20 minutes and 2 seconds
3 hours, 20 minutes and 1 seconds
3 hours, 20 minutes
3 hours, 19 minutes and 59 seconds
.
.
.

When I want to show:

3 hours, 20 minutes and 5 seconds
3 hours, 20 minutes and 4 seconds
3 hours, 20 minutes and 3 seconds
3 hours, 20 minutes and 2 seconds
3 hours, 20 minutes and 1 seconds
3 hours, 20 minutes and 0 seconds
3 hours, 19 minutes and 59 seconds
.
.
.

Is there an option for this? Without the code that i added?

Regards

**Comment by mckamey** [comment]
Ah I see. What you consider a "bug" is by design. No human lists all the zeros when talking about a time span. So changing it for how you like it would break everyone else.

The good news is that you don't need to change the library to make zero units display. You could just write your own custom formatting. For example, here is an example from another issue where zeros (and even leading zeros for minutes & seconds) were required.

[#4 (comment)](https://github.com/mckamey/countdownjs/issues/4#issuecomment-109644816)

**Comment by mcendon** [comment]
I understand. Thanks!

**Pull request closed without merging**
